version: '3'

services:
  db:
    image: postgres:12.4
    container_name: postgres
    restart: always
    ports:
      - 5430:5432
    volumes:
      - ./database/postgres:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#    command: postgres

  server:
    image: tomcat_cust
    container_name: tomcat
#    restart: always
    ports:
      - 8888:8080
    volumes:
      - ./target:/usr/local/tomcat/webapps/
      - ./tomcat/conf:/usr/local/tomcat/conf/
    environment:
      CATALINA_BASE:   /usr/local/tomcat
      CATALINA_HOME:   /usr/local/tomcat
      CATALINA_TMPDIR: /usr/local/tomcat/temp
      CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
    command: catalina.sh run
    links:
      - db